#!/usr/bin/env python3
"""Dev server for the mini-games monorepo.

Stdlib only. Two jobs:
  1. Serve static files from repo root.
  2. Expose GET /api/games -> JSON catalog, generated by scanning games/*/meta.json.

Run:  python3 serve.py [--port 8000] [--host 127.0.0.1]
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import os
import sys
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GAMES_DIR = ROOT / "games"

mimetypes.add_type("application/javascript", ".js")
mimetypes.add_type("text/css", ".css")


def scan_games() -> list[dict]:
    """Build catalog from games/<slug>/meta.json. Missing meta.json still lists the game."""
    if not GAMES_DIR.is_dir():
        return []

    games: list[dict] = []
    for entry in sorted(GAMES_DIR.iterdir()):
        if not entry.is_dir() or entry.name.startswith((".", "_")):
            continue
        if not (entry / "index.html").is_file():
            continue

        meta: dict = {}
        meta_path = entry / "meta.json"
        if meta_path.is_file():
            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                print(f"[warn] bad meta.json in {entry.name}: {exc}", file=sys.stderr)

        games.append(
            {
                "slug": entry.name,
                "url": f"/games/{entry.name}/",
                "title": meta.get("title", entry.name.replace("-", " ").title()),
                "description": meta.get("description", ""),
                "tags": meta.get("tags", []),
                "status": meta.get("status", "wip"),
                "controls": meta.get("controls", ""),
            }
        )
    return games


class GameCatalogHandler(SimpleHTTPRequestHandler):
    server_version = "MiniGamesDev/1.0"

    def end_headers(self) -> None:
        # Dev server: never serve stale JS/HTML after an edit.
        self.send_header("Cache-Control", "no-store, must-revalidate")
        super().end_headers()

    def do_GET(self) -> None:  # noqa: N802
        if self.path.split("?")[0] == "/api/games":
            body = json.dumps(scan_games(), indent=2).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        super().do_GET()

    def log_message(self, format: str, *args) -> None:  # noqa: A002
        sys.stderr.write(f"[{self.log_date_time_string()}] {format % args}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()

    games = scan_games()
    handler = partial(GameCatalogHandler, directory=str(ROOT))

    with ThreadingHTTPServer((args.host, args.port), handler) as httpd:
        print(f"mini-games dev server  ->  http://{args.host}:{args.port}/")
        print(f"catalog: {len(games)} game(s): {', '.join(g['slug'] for g in games) or '(none)'}")
        print("Ctrl+C to stop")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nstopped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
